export enum AnalyticsEvent {
  HelloApi = 'HelloApi',
  ApiCall = 'ApiCall',
  TrackingAccountDeactivated = 'TrackingAccountDeactivated',
  Refresh = 'Refresh',
  DeactivateAccount = 'DeactivateAccount',
  TrackCheck = 'TrackCheck',
  BalanceTrack = 'BalanceTrack',
  TrackWatch = 'TrackWatch',
  StealMeme = 'StealMeme',
  StartGame = 'StartGame',
  EndGame = 'EndGame',
  CVShown = 'CVShown',
  GithubLinkClicked = 'GithubLinkClicked',
  WhatsappLinkClicked = 'WhatsappLinkClicked',
  LinkedInLinkClicked = 'LinkedInLinkClicked',
  EmailLinkClicked = 'EmailLinkClicked',
  SetShortCvFormat = 'SetShortCvFormat',
  SetDetailedCvFormat = 'SetDetailedCvFormat',
  SetContrastCvView = 'SetContrastCvView',
  SetDefaultCvView = 'SetDefaultCvView',
  RepositoryClicked = 'RepositoryClicked',
  DemoClicked = 'DemoClicked',
}
